### ISSUE TITLE
Add the linter into golangci-lint

### ISSUE THREAD

**Issue by orsinium** [dgryski/semgrep-go#15]
Why the project isn't in [golangci-lint](https://github.com/golangci/golangci-lint)?

https://golangci-lint.run/contributing/new-linters/

**Comment by cristaloleg** [comment]
Probably it should be integrated from `golangci-lint` side? 👀

**Comment by orsinium** [comment]
Yes, for sure. However, let's see if the maintainer isn't against it and/or want to contribute the integration.

**Comment by dgryski** [comment]
I have no opinion here. The golangci-lint team are free to add semgrep integration into their tool and include my rules.

**Comment by rc-mattschwager** [comment]
Heads up, I created this task to track an integration here: https://github.com/golangci/golangci-lint/issues/2408
