### ISSUE TITLE
License

### ISSUE THREAD

**Issue by orsinium** [dgryski/semgrep-go#16]
What's the project license? I can't find a `LICENSE` file.

**Comment by quasilyte** [comment]
Use case:

* You have a proprietary project with closed source
* You want to use this repository rule files

=> Does the license permit this?

**Comment by aknuds1** [comment]
We are wondering about exactly the same! We want to include these rules in [Grafana](https://github.com/grafana/grafana/pull/28419), but are wondering how they are licensed.

**Comment by dgryski** [comment]
My little playground has grown much larger than expected.  I'm happy to add Apache or MIT (which is what I normally choose for my code).  Any opinions?

**Comment by aknuds1** [comment]
Whichever is probably fine. IANAL 🙂

**Comment by dgryski** [comment]
I would also like my rules to be compatible / consistent with the "official" collection of rules.

The upstream issue: https://github.com/returntocorp/semgrep-rules/issues/899

**Comment by orsinium** [comment]
[Semgrep](https://github.com/returntocorp/semgrep) is [licensed under LGPL-2.1](https://github.com/returntocorp/semgrep/blob/develop/LICENSE). Until you don't make distributions that include semgrep inside, you free to use any license you like. See point 5 for details.

**Comment by dgryski** [comment]
There is discussion that the semgrep-rules repository is "data" and that they will license it under CC-BY-SA.  I'm waiting too see how that resolves.  I will match the upstreeam rules license.

**Comment by mschwager** [comment]
Hi all,

Just wanted to let you know that we've completed the `semgrep-rules` licensing issue and have documented the results in more plain language here: https://semgrep.dev/docs/faq/#how-are-semgrep-and-its-rules-licensed. Hope this helps :+1:

**Comment by dgryski** [comment]
Went with MIT

**Comment by aknuds1** [comment]
Thanks @dgryski!
