### ISSUE TITLE
Flag comparison of Unix nanotime instead of Before/After?

### ISSUE THREAD

**Issue by ainar-g** [dgryski/semgrep-go#31]
(Following the discussion in dominikh/go-tools#995.)

Unless the intention of the programmer was to check if the system's wall clock went backwards, code like:

```go
t1.UnixNano() >= t2.UnixNano()
```

Should be simplified to:

```go
!t1.Before(t2)
```

Same with other operators.

I think I could write this check myself, but I'm not sure when I will have the time to do it.

**Comment by dgryski** [comment]
Sounds good to me.
